env:
  browser: true
  es6: true
extends:
  - google
  - plugin:react/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
parser: "@babel/eslint-parser"
rules: {}
ignorePatterns: ["tyko/static/pack/*"]
overrides:
  - files: [ "**/*.{ts,tsx}" ]
    env:
      jest: true
    globals:
      React: "writable"
    settings:
      import/parsers:
        "@typescript-eslint/parser": [ ".ts", ".tsx" ]
      import/resolver:
        typescript:
          project: "./tsconfig.json"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: "./tsconfig.json"
    extends: [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:react/recommended",
        "plugin:import/errors",
        "plugin:import/warnings",
        "plugin:import/typescript",
        "plugin:react-hooks/recommended",
    ]
