version: '2.4'
services:

  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000  "tyko.run:create_app(\"mysql://avuser:avpsw@db:3306/av_preservation\")"
  db:
    image: 'mariadb'
#    build:
#      context: ..
#      dockerfile: database/Dockerfile
    ports:
      - "8006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=av_preservation
      - MYSQL_USER=avuser
      - MYSQL_PASSWORD=avpsw
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - avdata:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
#      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 2s
      timeout: 20s
      retries: 10
#      start_period: 40s


volumes:
  avdata: