FROM python:3.9 as base_image
RUN apt -y update && \
    apt install -y npm
RUN npm install -g npm && \
    mkdir /.npm && \
    chmod 777 /.npm

FROM base_image as wheel_builder
COPY CI/docker/jenkins/requirements-ci.txt requirements.txt ./
RUN python -m pip install pip --upgrade
RUN python -m pip install wheel

RUN pip wheel -w /wheels/ \
    -r requirements-ci.txt \
    -r requirements.txt

FROM base_image
COPY --from=wheel_builder /wheels /wheels/
COPY CI/docker/jenkins/requirements-ci.txt requirements.txt ./
RUN pip install --no-cache-dir --no-index --find-links=/wheels/ \
    -r requirements-ci.txt \
    -r requirements.txt