on: [push]
name: SonarQube

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pytest:
    name: Run Python tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: Cache python dependendies
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: |
       coverage run --parallel-mode --branch --source=tyko,tests -m pytest --junitxml=reports/test-report.xml
       coverage combine
       coverage xml -o coverage-reports/pythoncoverage-pytest.xml
       sed -i 's/\/home\/runner\/work\/tyko\/tyko/\/github\/workspace/g' coverage-reports/pythoncoverage-pytest.xml
       sed -i 's/\/home\/runner\/work\/tyko\/tyko/\/github\/workspace/g' reports/test-report.xml
       cat coverage-reports/pythoncoverage-pytest.xml
    - name: Upload pytest report
      uses: actions/upload-artifact@v1
      with:
        name: pytest-report
        path: reports/test-report.xml

  sonarCloudTrigger:
    needs: pytest
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: Get pytest report
      uses: actions/download-artifact@v1
      with:
        name: pytest-report
        path: reports/test-report.xml
    - name: debug
      run: ls -la
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
